import './globals.css'
import type { Metadata } from 'next'
import Providers from './providers'
import ThemeSwitcher from './theme/ThemeSwitcher'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ThemeSwitcher />
            {children}
        </Providers>
      </body>
    </html>
  )
}
